services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=ton.email@genolier.ch"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
      - ./budgetis/media:/media:ro

    networks:
      - budgetis

  media:
    image: nginx:alpine
    volumes:
      - ./nginx/media.conf:/etc/nginx/nginx.conf:ro
      - media_data:/usr/share/nginx/html/media
    expose:
      - "80"
    networks:
      - budgetis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.media.rule=Host(`budgetis.genolier.ch`) && PathPrefix(`/media/`)"
      - "traefik.http.routers.media.entrypoints=websecure"
      - "traefik.http.routers.media.tls.certresolver=letsencrypt"
      - "traefik.http.services.media.loadbalancer.server.port=80"

  web:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    entrypoint: [ "/app/docker/entrypoint.sh" ]
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    labels:
      - "traefik.enable=true"

      # Router HTTPS
      - "traefik.http.routers.budgetis.rule=Host(`budgetis.genolier.ch`)"
      - "traefik.http.routers.budgetis.entrypoints=websecure"
      - "traefik.http.routers.budgetis.tls.certresolver=letsencrypt"

      # Router HTTP -> HTTPS
      - "traefik.http.routers.budgetis_http.rule=Host(`budgetis.genolier.ch`)"
      - "traefik.http.routers.budgetis_http.entrypoints=web"
      - "traefik.http.routers.budgetis_http.middlewares=redirect-to-https"

      # Middleware
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

      # Rate limiting global
      - "traefik.http.middlewares.global-ratelimit.ratelimit.average=60"
      - "traefik.http.middlewares.global-ratelimit.ratelimit.burst=200"
      - "traefik.http.middlewares.global-ratelimit.ratelimit.period=1m"

      # Rate limiting for login
      - "traefik.http.routers.login.rule=Path(`/admin/login/`)"
      - "traefik.http.routers.login.entrypoints=websecure"
      - "traefik.http.routers.login.middlewares=login-ratelimit@docker"
      - "traefik.http.services.login.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.login-ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.login-ratelimit.ratelimit.burst=10"
      - "traefik.http.middlewares.login-ratelimit.ratelimit.period=1m"
    networks:
      - budgetis
    volumes:
      - static_data:/app/static
      - media_data:/app/media

  celery:
    build:
      context: .
      dockerfile: docker/celery.Dockerfile
    labels:
      - "traefik.enable=false"
    networks:
      - budgetis

  celery-beat:
    build:
      context: .
      dockerfile: docker/celery.Dockerfile
    labels:
      - "traefik.enable=false"
    networks:
      - budgetis

volumes:
  letsencrypt:
  static_data:
  media_data:

networks:
  budgetis:
    external: false
